### ISSUE TITLE
Connect a 3D object to more than one place

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/multimodal-map#80]
Some models, for instance of a necropolis piazza, are of interest for a lot of tombs (all facing the piazza). If a 3d object, just like a document, could be associated with many places this would be much more intuitive and save a lot of time.

**Comment by mtomasini** [comment]
3D objects are coded in Diana as a link to the model (the model itself is saved on the server) and a series of coordinates as starting point, as well as a related tomb. So I thought that the best way to refer to the same tomb was to create a new object in Diana for each tomb: this allows you to have custom starting point in the 3D model for each tomb.

If we make it so that you can assign two or more tombs to the same 3D object, then all those tombs will point to the same point with the same starting coordinate on the 3D model. (It's easy to do, it's just that I'm not sure that's what we wanted, from previous discussions)

**Comment by mtomasini** [comment]
This is fixed now (see commits in https://github.com/gu-gridh/etruscantombs/commits).
